### ISSUE TITLE
Recent beep() problem with Linux... and fix proposal

### ISSUE THREAD

**Issue by jourquin** [rasmusab/beepr#11]
Hi,

Thank you for this useful small package.

The beep function doesn't work anymore on my computer, returning that "no audio drivers are available"

I've recently upgraded my Linux Fedora box from release 21 to 22, and also upgraded all my R packages. So, I don't know if the problem is related to some R packages or the Linux distribution.

It comes out that the problem is not related to the audio driver, but that it finds its origin in the "is_wav_fname" function, which returns FALSE even if fname is a valid wav file. 

"is_wav_fname" uses "ignore.case("\\.wav$"), which is deprecated.

So, I replaced 
"str_detect(fname, ignore.case("\\.wav$"))
by
"str_detect(fname, fixed(".wav", ignore_case=TRUE))

 and this solves the problem.

Bart

**Comment by rasmusab** [comment]
Hi,

thanks for reporting this! This should be fixed now and uploaded to CRAN! Could you update and see if the problem has been resolved for you?

**Comment by jourquin** [comment]
Hi,

Yes, it works indeed. Thanks.

Bart

De : Rasmus Bååth <notifications@github.com<mailto:notifications@github.com>>
Répondre à : rasmusab/beepr <reply@reply.github.com<mailto:reply@reply.github.com>>
Date : mercredi 17 juin 2015 12:15
À : rasmusab/beepr <beepr@noreply.github.com<mailto:beepr@noreply.github.com>>
Cc : bart <bart.jourquin@uclouvain.be<mailto:bart.jourquin@uclouvain.be>>
Objet : Re: [beepr] Recent beep() problem with Linux... and fix proposal (#11)


Hi,

thanks for reporting this! This should be fixed now and uploaded to CRAN! Could you update and see if the problem has been resolved for you?

-

**Comment by rasmusab** [comment]
Great!
