### ISSUE TITLE
quiet hours

### ISSUE THREAD

**Issue by dougmitarotonda** [rasmusab/beepr#14]
I love your package and use it all the time. I'd love it if you could add "quiet hours" logic as to whether to actually beep or not. For long runs I kickoff before bed I sometimes forget to mute my machine and have woken up to the beep! 

The first pass implementation of this would be to just pass a character vector to `beep` like `c("22:00", "07:00")` (defaults to `NULL`, i.e., doesn't respect quiet time so as not to break current usage) and then compare against "now" (`chron::times` might be a good approach internally to convert the input and compare it to the `Sys.time`). This is pretty straight forward and I could submit a PR if this is something you'd be willing to add.

A next step off of this would be to build an `options` argument that can be set globally for the package so you don't have to pass it in with each `beep` call. I've seen this in other packages, but haven't done it myself, so I'd have to research a bit more how it is done. 

Anyway, let me know what you think.

**Comment by rasmusab** [comment]
Hi Dough!

I prefer to keep beeper pretty simple, just sounds and nothing else :) But the behavior you describes sounds like a perfect job for a function wrapping `beep`!
