### ISSUE TITLE
Could this work in a Shiny app?

### ISSUE THREAD

**Issue by sterfa02** [rasmusab/beepr#15]
I love this package and use it a lot! I recently tried it in a Shiny app and could not get the sound to go in a deployed app. It works perfectly when I use shiny::runApp() from Rstudio. My deployed Shiny app's log shows the package loading fine and no errors related to the Beepr package. Is there something fundamental to a Shiny app that would prevent it from working?

**Comment by rasmusab** [comment]
The sound should be made but on the Server. As long as the server and client is on the same computer it works, like when you run Shiny locally, but if you want to make sounds purely on the client you would have to use some other method.
