### ISSUE TITLE
Beep on error

### ISSUE THREAD

**Issue by aedobbyn** [rasmusab/beepr#20]
Hello! This is a great package.

What do you think about an extension to only beep on error? Something along the lines of:

```
library(beepr)

beep_on_error <- function(inp, error_beep = 9) {
  q_inp <- substitute(inp)
  
  msg <- paste0("An error occurred in ", deparse(q_inp))
  e <- simpleError(msg)
  
  tryCatch(inp, error = function(e) {
    message(paste0(msg, ": ", e$message))
    beep(error_beep)
  })
}

beep_on_error(log("foo"))
#> An error occurred in log("foo"): non-numeric argument to mathematical function

beep_on_error(log(3))
#> [1] 1.098612
```

This doesn't work with the forwards pipe but maybe it's worth looking into. If you like, I'm happy to submit a PR.

**Comment by rasmusab** [comment]
This is a great suggestion! :) Please feel free to make a pull request. However, I would prefer if we try to mimic the call of beep as closely as possible, for example using:

```
beep_on_error(expr, sound = 1)
```

**Comment by aedobbyn** [comment]
Oh for sure!

**Comment by rasmusab** [comment]
Added in #21 .
