### ISSUE TITLE
beepr with RStudio server?

### ISSUE THREAD

**Issue by ignacio82** [rasmusab/beepr#25]
It looks like [it is possible](https://www.youtube.com/watch?v=nHJQGnorneo) to use beepr with RStudio server but i could not find a tutorial. This is what I get when I try to run it:

```r
> beepr::beep(4)
Warning message:
In value[[3L]](cond) :
  beep() could not play the sound due to the following error:
Error in play.default(x, rate, ...): no audio drivers are available
```

Could you point me in the right direction?

**Comment by rasmusab** [comment]
So beepr plays the sund on the physical computer where it's run. So if the actual code is run on a server, which is likely the case when you run Rstudio server, then beepr wont work, unfortunately.
