### ISSUE TITLE
Can't play beepR in Arch Linux

### ISSUE THREAD

**Issue by marcofaga** [rasmusab/beepr#28]
Hi. Im using Arch Linux with Rstudio. 

Unfortunately,  beepr is not working. 

I run beep() function and nothing happens. My audio cards are ok.

Any idea of whats happening?

**Comment by rasmusab** [comment]
Do you have any of the following programs available on the command line?

```
paplay
aplay
vlc
```

If no, does beepr work if you install `vlc` (like this, I think: `pacman -S vlc`)?

**Comment by marcofaga** [comment]
Yes. I already have all of them. I reinstalled vlc, but nothing happens.

**Comment by rasmusab** [comment]
Hmmm, ok then I would be super grateful if you would try out the following to try figure out where things go wrong:

1. Try running `beepr::beep()` in an R session started from the terminal. (So not Rstudio).
2. Try running the following commands in an R session:
```
fname <- system.file("sounds/microwave_ping_mono.wav", package = "beepr")
system(paste0("aplay --buffer-time=48000 -N -q ", fname))
system(paste0("paplay  ", fname))
system(paste0("vlc -Idummy --no-loop --no-repeat --playlist-autostart --no-media-library --play-and-exit  ", fname))
```

Did any of the approaches above work?

**Comment by marcofaga** [comment]
Hi!!

The aplay method works well. 

With vlc method I can hear the beep, but returns the message:  

> lcpulse audio output error: PulseAudio server connection failure: Connection refused
> [000055cc345120f0] dummy interface: using the dummy interface module...
> [000055cc34441190] main playlist: end of playlist, exiting


The paplay method doesn't return any sound and show the message: 

> 
> Connection failure: Connection refused
> pa_context_connect() failed: Connection refused


The beep function still not working.

**Comment by rasmusab** [comment]
`beepr` tries the methods in this order: paplay, aplay and finally vlc. If any of these three programs are in your path it will be used. As you have paplay installed, but it doesn't work for you, then beepr will use it and you'll get no sound. You have two ways you can get beepr working:

1. Fix paplay so that it works.
2. Remove paplay so that beepr falls back on using aplay.

Sorry for the annoying solution :)
