### ISSUE TITLE
WISH: beep("none") and beep(sound = -1)

### ISSUE THREAD

**Issue by HenrikBengtsson** [rasmusab/beepr#29]
It could be convenient to be able to call `beep(sound)` as a noop, i.e. such that it returns immediately if `sound = -1` or `sound = "none".

**Comment by HenrikBengtsson** [comment]
An alternative to `-1L`, since `sound = 0L` is already taken, is to use `sound = NA_integer_` for silence.

**Comment by rasmusab** [comment]
Addressed by https://github.com/rasmusab/beepr/commit/48b1248d55ef105c36c0c312611b934b2a51a0fc
