### ISSUE TITLE
Feature request: Make sound play when finished knitting

### ISSUE THREAD

**Issue by givison** [rasmusab/beepr#31]
Unsure if there's some solution that already exists, but it would be great if I could get this to play a sound when a markdown document has finished knitting.

Thanks for a great package!
Geoff

**Comment by rasmusab** [comment]
This seems like a solution for your problem :)

https://stackoverflow.com/questions/46313915/run-alert-on-completion-of-knitr-build

**Comment by givison** [comment]
Thanks!
