### ISSUE TITLE
Project says GPL-3.0 license, but includes sounds from video games

### ISSUE THREAD

**Issue by mgavin** [rasmusab/beepr#32]
Since sounds used within beepr are from Final Fantasy, Warcraft 2, Facebook, DOOM, etc., I think it may clash with the validity of the package license when the files are included in the distribution of the package itself.

I think removing them would help the distribute-ability of the package and help keep compliance with the license. Instead, they can just be made links to resource files to other places, since the package supports playing sounds from a url.
Like
`beep("http://www.wolfensteingoodies.com/archives/olddoom/sounds/dsshotgn.wav")`
instead of
`beep(7)`

**Comment by rasmusab** [comment]
This is something I've been thinking about. I don't like the solution that the package would need internet connectivity to work, and I like that the package is self contained. I'm aware that these sounds come from popular video games from the 90s, but I believe the short sound snippets I use in the package go under "fair use".
