### ISSUE TITLE
Some of the sounds have a stutter

### ISSUE THREAD

**Issue by pnacht** [rasmusab/beepr#36]
On Windows 10 x64, R 4.0.2, Rstudio 1.3.1056, some of the sounds seem to have a stutter, repeating the last millisecond of the sound.

By ear, I can hear it on "complete", "ready", "shotgun", and "sword".

It's trivial and in no way harms the functional purpose of the (very useful!) package, but just thought it best to report this.

**Comment by mattbk** [comment]
Is this the same as #34?

**Comment by rasmusab** [comment]
I don't know why, but converting these four sounds from 11Hz to 22Hz seems to have fixed it. At least on the Windows machine I got my hands on. Fixed by this commit: https://github.com/rasmusab/beepr/commit/f3f6fd9917e78e06899e26639a161ba788ce2e16
