### ISSUE TITLE
Sound request: old Windows "tada" and "critical stop" sounds

### ISSUE THREAD

**Issue by mike-lawrence** [rasmusab/beepr#37]
Dunno if you're taking inclusion requests, but these classics would be top for me:
[Tada](https://www.myinstants.com/instant/windows-31-startup-tada/)
[Critical Stop](https://www.myinstants.com/instant/windows-xp-critical-stop-27303/)

**Comment by rasmusab** [comment]
These sound suggestions are great! But, despite how fun it would b to include these, I've decided to close the door on any new sounds. But feel free to fork and make your own customized R sound package! :D
