### ISSUE TITLE
Rstudio Jobs and beepR

### ISSUE THREAD

**Issue by gowachin** [rasmusab/beepr#38]
Hi, 

Since Rstudio 1.2, we can run different jobs in background. (See [this article](https://www.rstudio.com/blog/rstudio-1-2-jobs/))
I tried to run a small script with a `beep()` call but I don't hear anything.

Example script
```
library(beepr)
Sys.sleep(2)
beep(1)
cat("Done \n")
```

Do you think it's possible to tweak Rstudio or the package in a way this can work ?

PS : Awesome package, thanks a lot !

**Comment by rasmusab** [comment]
This should work, however, the problem here is that immediately after `beep(1)` the script ends. which also kills the sound, which barely get any time to play. If you try the following script, you should get a sound:

```
library(beepr)
Sys.sleep(2)
beep(1)
Sys.sleep(2)
cat("Done \n")
```
