### ISSUE TITLE
paplay not working with Ubuntu 20.04

### ISSUE THREAD

**Issue by DunderChief** [rasmusab/beepr#39]
Perhaps it's specific to my system, but no sound comes from paplay when playing wav files (no error also). play_aplay() and play_vlc() both work.

Maybe aplay could be first in the if/else hierarchy of play_file(). Or add an option to choose which program to use with beep().

**Comment by rasmusab** [comment]
Addressed by https://github.com/rasmusab/beepr/commit/6a3e199a7b00f923cd1c0af35dde2c4d7bce191d .
