### ISSUE TITLE
Add URL and BugReports to DESCRIPTION

### ISSUE THREAD

**Issue by HenrikBengtsson** [rasmusab/beepr#40]
Please consider adding fields `URL` and `BugReports` to the DESCRIPTION file to make it easy to locate this repo, e.g. from https://cran.r-project.org/package=beepr.

**Comment by rasmusab** [comment]
Addressed by https://github.com/rasmusab/beepr/commit/07c898d4464d92ae39ad3a09ecc0e7be5dc94586 (But will still need to be updated on CRAN...)
