### ISSUE TITLE
BUG: MS Windows requires download.file(..., mode = "wb")

### ISSUE THREAD

**Issue by HenrikBengtsson** [rasmusab/beepr#41]
`beep(url)` uses:

https://github.com/rasmusab/beepr/blob/07c898d4464d92ae39ad3a09ecc0e7be5dc94586/R/beepr.R#L66

to download the file.  However, `download.file()` defaults to `mode = "w"` (text mode), which works fine on Linux and macOS, but on MS Windows, it'll automagically turn `\n` (LF) into `\r\n` (CRLF) and vice versa, also in binary files.  To avoid this, explicitly specify `mode = "wb"`, i.e.

```r

        if(download.file(sound, destfile = temp_file, mode = "wb", quiet = TRUE) == 0) { # The file was successfully downloaded
```

**Comment by rasmusab** [comment]
Fixed by https://github.com/rasmusab/beepr/commit/0d8cdbb774fac24f4614c812b3346c5fc25e451c
