### ISSUE TITLE
WISH: Make package lightweight by dropping dependency on 'stringr'

### ISSUE THREAD

**Issue by HenrikBengtsson** [rasmusab/beepr#42]
The 'stringr' package depends on 'stringi', which is quite heavy and takes a long time to install from source.  Looking at the source code, 'beepr' uses:

* `stringr::str_detect()`
* `stringr::str_replace_all()`
* `stringr::str_trim()`

These can easily be replaced by `base::grepl()` and `base::gsub()`, e.g.

```r
str_detect <- function(string, pattern, ignore_case = TRUE) {
  grepl(pattern, string, ignore.case = ignore_case)
}

str_replace_all <- function (string, pattern, replacement) {
  gsub(pattern, replacement, string)
}

str_trim <- function(string) {
  gsub("(^[[:space:]]+|[[:space:]]+$)", "", string)
}
```

Doing so would make 'beepr' depend on only 'audio'.

**Comment by rasmusab** [comment]
Addressed by https://github.com/rasmusab/beepr/commit/526fd650877862502d749d4ad9e948453414e271
