### ISSUE TITLE
beep() cannot play sounds from paths beginning with most punctuation marks

### ISSUE THREAD

**Issue by rossellhayes** [rasmusab/beepr#47]
`beep()` contains a test to see if `sound` is less than 0. If so, it plays no sound. However, it doesn't first check if `sound` is a number. This can lead to unintended behavior if `sound` is a path to a file beginning with a character that is alphabetized before 0. This is particularly a problem on Mac and Linux, where file paths generally start with either `/` or `~`. In most locales, both are sorted before 0, meaning sounds from paths beginning with `/` or `~` will never play.

**Comment by rasmusab** [comment]
Ah, yeah, I see that now. Fixed by f4493fdf6cc42384873decb4cb8e0c634fb58954 . Thanks for reporting!
